project: Fix builds by upgrading to Ruby 3.3
Fixes:

ERROR:  Error installing bundler:
        The last version of bundler (>= 0) to support your Ruby &
        RubyGems was 2.4.22. Try installing it with `gem install
        bundler -v 2.4.22`
        bundler requires Ruby version >= 3.0.0.
        The current ruby version is 2.7.8.225.

Fixes:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

nokogumbo.c: In function ‘wrap_parse_args’:
nokogumbo.c:492:27: error: ‘rb_cData’ undeclared (first use in this
function)

In Gemfile:
  forspell was resolved to 0.0.8, which depends on
      sanitize was resolved to 5.2.3, which depends on
            nokogumbo
An error occurred while installing nokogumbo (2.0.5), and Bundler
cannot continue.